### ISSUE TITLE
Commited API key to repo

### ISSUE THREAD

**Issue by mattkduran** [Rikozi/ipportcheck#1]
Hi there,
It looks like you accidentally committed your Shodan API key to your repo (line 88 in ipportcheck.py). You should follow the steps that Github outlines here on removing it from your repo history:

https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Thanks!
Matt

**Comment by Rikozi** [comment]
thank you for your report shodan ip key is just for test account
